export const headerActionTypes = {
    FETCH_HEADER_DATA_START: 'FETCH_HEADER_DATA_START',
    FETCH_HEADER_DATA_SUCCESS: 'FETCH_HEADER_DATA_SUCCESS',
    FETCH_HEADER_DATA_FAILURE: 'FETCH_HEADER_DATA_FAILURE'
}