export const headerActionTypes = {
    FETCH_HEADER_DATA_START: 'FETCH_HEADER_DATA_START', 
    SET_HEADER_DATA: `SET_HEADER_DATA`,
    GET_QUICK_LINKS: 'GET_QUICK_LINKS',
    GET_TAB_ITEMS_DATA: 'GET_TAB_ITEMS_DATA'
}