const tempNewsDataActionTypes = {
    FETCH_NEWS_DATA_START: 'FETCH_NEWS_DATA_START',
    FETCH_NEWS_DATA_SUCCESS: 'FETCH_NEWS_DATA_SUCCESS',
    FETCH_NEWS_DATA_NEXT_PAGE: 'FETCH_NEWS_DATA_NEXT_PAGE',
    FETCH_NEWS_DATA_FAILURE: 'FETCH_NEWS_DATA_FAILURE'    
};

export default tempNewsDataActionTypes;