export const announcementsActionTypes = {
    GET_INITIAL_ANNOUNCEMENTS_START: 'GET_INITIAL_ANNOUNCEMENTS_START',
    GET_INITIAL_ANNOUNCEMENTS_SUCCESS: 'GET_INITIAL_ANNOUNCEMENTS_SUCCESS',
    GET_INITIAL_ANNOUNCEMENTS_FAILURE: 'GET_INITIAL_ANNOUNCEMENTS_FAILURE'
}