export const shoppingCardActionTypes = {
    ADD_ITEM_TO_CARD: `ADD_ITEM_TO_CARD`,
    REMOVE_ITEM_FROM_CARD: 'REMOVE_ITEM_FROM_CARD',
    SET_ITEM_QUANTITY: 'SET_ITEM_QUANTITY',
    CLEAR_CARD: 'CLEAR_CARD'
}